---

- name: Azure AD VMS
  azure_vms:
      virtual_machine_username        : "{{ azure_vms_virtual_machine_username }}"
      virtual_machine_password        : "{{ azure_vms_virtual_machine_password }}" # The password has to be complex (letters BIG/small , numbers, ..etc)
      virtual_machine_name            : "{{ azure_vms_virtual_machine_name }}"
      location                        : "{{ azure_vms_location }}" #The location e.g. westeurope
      virtual_machine_storage_name    : "{{ azure_vms_virtual_machine_storage_name }}" #The storage account name e.g. azuresandboxsa
      virtual_network_name            : "{{ azure_vms_virtual_network_name }}" #The virtual Network name e.g. azuresandboxvn
      security_group                  : "{{ azure_vms_security_group }}" #The security group name to create the NIC
      virtual_machine_source_image    : "{{ azure_vms_virtual_machine_source_image }}" #e.g. https://azure123tgdf.blob.core.windows.net/vhds/image.vhd this MUST be in the same resource group as the VM itself.
      resource_group_name             : "{{ azure_vms_resource_group_name }}"
